# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/message.proto',
  package='tfedlrn',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13proto/message.proto\x12\x07tfedlrn\":\n\x0bTensorProto\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x0e\n\x06values\x18\x03 \x03(\x02\"Z\n\rMessageHeader\x12\x0e\n\x06sender\x18\x01 \x02(\t\x12\x11\n\trecipient\x18\x02 \x02(\t\x12\x15\n\rfederation_id\x18\x03 \x02(\t\x12\x0f\n\x07\x63ounter\x18\x04 \x02(\x05\"P\n\nModelProto\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\x05\x12%\n\x07tensors\x18\x03 \x03(\x0b\x32\x14.tfedlrn.TensorProto\"q\n\x10LocalModelUpdate\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\x12\"\n\x05model\x18\x02 \x02(\x0b\x32\x13.tfedlrn.ModelProto\x12\x11\n\tdata_size\x18\x03 \x02(\x05\"Q\n\x16LocalValidationResults\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\x12\x0f\n\x07results\x18\x02 \x02(\x02\"4\n\nJobRequest\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\">\n\x14ModelDownloadRequest\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\"_\n\x11GlobalModelUpdate\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\x12\"\n\x05model\x18\x02 \x02(\x0b\x32\x13.tfedlrn.ModelProto\"M\n\x08JobReply\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\x12\x19\n\x03job\x18\x02 \x02(\x0e\x32\x0c.tfedlrn.Job\"2\n\x08TrainAck\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader\"7\n\rValidationAck\x12&\n\x06header\x18\x01 \x02(\x0b\x32\x16.tfedlrn.MessageHeader*[\n\x03Job\x12\r\n\tJOB_TRAIN\x10\x00\x12\x10\n\x0cJOB_VALIDATE\x10\x01\x12\r\n\tJOB_YIELD\x10\x02\x12\x0c\n\x08JOB_QUIT\x10\x03\x12\x16\n\x12JOB_DOWNLOAD_MODEL\x10\x04')
)

_JOB = _descriptor.EnumDescriptor(
  name='Job',
  full_name='tfedlrn.Job',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOB_TRAIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOB_VALIDATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOB_YIELD', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOB_QUIT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOB_DOWNLOAD_MODEL', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=867,
  serialized_end=958,
)
_sym_db.RegisterEnumDescriptor(_JOB)

Job = enum_type_wrapper.EnumTypeWrapper(_JOB)
JOB_TRAIN = 0
JOB_VALIDATE = 1
JOB_YIELD = 2
JOB_QUIT = 3
JOB_DOWNLOAD_MODEL = 4



_TENSORPROTO = _descriptor.Descriptor(
  name='TensorProto',
  full_name='tfedlrn.TensorProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tfedlrn.TensorProto.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='tfedlrn.TensorProto.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='tfedlrn.TensorProto.values', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=90,
)


_MESSAGEHEADER = _descriptor.Descriptor(
  name='MessageHeader',
  full_name='tfedlrn.MessageHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='tfedlrn.MessageHeader.sender', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recipient', full_name='tfedlrn.MessageHeader.recipient', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='federation_id', full_name='tfedlrn.MessageHeader.federation_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='tfedlrn.MessageHeader.counter', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=182,
)


_MODELPROTO = _descriptor.Descriptor(
  name='ModelProto',
  full_name='tfedlrn.ModelProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tfedlrn.ModelProto.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='tfedlrn.ModelProto.version', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tensors', full_name='tfedlrn.ModelProto.tensors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=264,
)


_LOCALMODELUPDATE = _descriptor.Descriptor(
  name='LocalModelUpdate',
  full_name='tfedlrn.LocalModelUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.LocalModelUpdate.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='tfedlrn.LocalModelUpdate.model', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_size', full_name='tfedlrn.LocalModelUpdate.data_size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=379,
)


_LOCALVALIDATIONRESULTS = _descriptor.Descriptor(
  name='LocalValidationResults',
  full_name='tfedlrn.LocalValidationResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.LocalValidationResults.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='tfedlrn.LocalValidationResults.results', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=462,
)


_JOBREQUEST = _descriptor.Descriptor(
  name='JobRequest',
  full_name='tfedlrn.JobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.JobRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=516,
)


_MODELDOWNLOADREQUEST = _descriptor.Descriptor(
  name='ModelDownloadRequest',
  full_name='tfedlrn.ModelDownloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.ModelDownloadRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=518,
  serialized_end=580,
)


_GLOBALMODELUPDATE = _descriptor.Descriptor(
  name='GlobalModelUpdate',
  full_name='tfedlrn.GlobalModelUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.GlobalModelUpdate.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='tfedlrn.GlobalModelUpdate.model', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=677,
)


_JOBREPLY = _descriptor.Descriptor(
  name='JobReply',
  full_name='tfedlrn.JobReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.JobReply.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='job', full_name='tfedlrn.JobReply.job', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=756,
)


_TRAINACK = _descriptor.Descriptor(
  name='TrainAck',
  full_name='tfedlrn.TrainAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.TrainAck.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=758,
  serialized_end=808,
)


_VALIDATIONACK = _descriptor.Descriptor(
  name='ValidationAck',
  full_name='tfedlrn.ValidationAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='tfedlrn.ValidationAck.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=865,
)

_MODELPROTO.fields_by_name['tensors'].message_type = _TENSORPROTO
_LOCALMODELUPDATE.fields_by_name['header'].message_type = _MESSAGEHEADER
_LOCALMODELUPDATE.fields_by_name['model'].message_type = _MODELPROTO
_LOCALVALIDATIONRESULTS.fields_by_name['header'].message_type = _MESSAGEHEADER
_JOBREQUEST.fields_by_name['header'].message_type = _MESSAGEHEADER
_MODELDOWNLOADREQUEST.fields_by_name['header'].message_type = _MESSAGEHEADER
_GLOBALMODELUPDATE.fields_by_name['header'].message_type = _MESSAGEHEADER
_GLOBALMODELUPDATE.fields_by_name['model'].message_type = _MODELPROTO
_JOBREPLY.fields_by_name['header'].message_type = _MESSAGEHEADER
_JOBREPLY.fields_by_name['job'].enum_type = _JOB
_TRAINACK.fields_by_name['header'].message_type = _MESSAGEHEADER
_VALIDATIONACK.fields_by_name['header'].message_type = _MESSAGEHEADER
DESCRIPTOR.message_types_by_name['TensorProto'] = _TENSORPROTO
DESCRIPTOR.message_types_by_name['MessageHeader'] = _MESSAGEHEADER
DESCRIPTOR.message_types_by_name['ModelProto'] = _MODELPROTO
DESCRIPTOR.message_types_by_name['LocalModelUpdate'] = _LOCALMODELUPDATE
DESCRIPTOR.message_types_by_name['LocalValidationResults'] = _LOCALVALIDATIONRESULTS
DESCRIPTOR.message_types_by_name['JobRequest'] = _JOBREQUEST
DESCRIPTOR.message_types_by_name['ModelDownloadRequest'] = _MODELDOWNLOADREQUEST
DESCRIPTOR.message_types_by_name['GlobalModelUpdate'] = _GLOBALMODELUPDATE
DESCRIPTOR.message_types_by_name['JobReply'] = _JOBREPLY
DESCRIPTOR.message_types_by_name['TrainAck'] = _TRAINACK
DESCRIPTOR.message_types_by_name['ValidationAck'] = _VALIDATIONACK
DESCRIPTOR.enum_types_by_name['Job'] = _JOB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TensorProto = _reflection.GeneratedProtocolMessageType('TensorProto', (_message.Message,), dict(
  DESCRIPTOR = _TENSORPROTO,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.TensorProto)
  ))
_sym_db.RegisterMessage(TensorProto)

MessageHeader = _reflection.GeneratedProtocolMessageType('MessageHeader', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEHEADER,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.MessageHeader)
  ))
_sym_db.RegisterMessage(MessageHeader)

ModelProto = _reflection.GeneratedProtocolMessageType('ModelProto', (_message.Message,), dict(
  DESCRIPTOR = _MODELPROTO,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.ModelProto)
  ))
_sym_db.RegisterMessage(ModelProto)

LocalModelUpdate = _reflection.GeneratedProtocolMessageType('LocalModelUpdate', (_message.Message,), dict(
  DESCRIPTOR = _LOCALMODELUPDATE,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.LocalModelUpdate)
  ))
_sym_db.RegisterMessage(LocalModelUpdate)

LocalValidationResults = _reflection.GeneratedProtocolMessageType('LocalValidationResults', (_message.Message,), dict(
  DESCRIPTOR = _LOCALVALIDATIONRESULTS,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.LocalValidationResults)
  ))
_sym_db.RegisterMessage(LocalValidationResults)

JobRequest = _reflection.GeneratedProtocolMessageType('JobRequest', (_message.Message,), dict(
  DESCRIPTOR = _JOBREQUEST,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.JobRequest)
  ))
_sym_db.RegisterMessage(JobRequest)

ModelDownloadRequest = _reflection.GeneratedProtocolMessageType('ModelDownloadRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODELDOWNLOADREQUEST,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.ModelDownloadRequest)
  ))
_sym_db.RegisterMessage(ModelDownloadRequest)

GlobalModelUpdate = _reflection.GeneratedProtocolMessageType('GlobalModelUpdate', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALMODELUPDATE,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.GlobalModelUpdate)
  ))
_sym_db.RegisterMessage(GlobalModelUpdate)

JobReply = _reflection.GeneratedProtocolMessageType('JobReply', (_message.Message,), dict(
  DESCRIPTOR = _JOBREPLY,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.JobReply)
  ))
_sym_db.RegisterMessage(JobReply)

TrainAck = _reflection.GeneratedProtocolMessageType('TrainAck', (_message.Message,), dict(
  DESCRIPTOR = _TRAINACK,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.TrainAck)
  ))
_sym_db.RegisterMessage(TrainAck)

ValidationAck = _reflection.GeneratedProtocolMessageType('ValidationAck', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATIONACK,
  __module__ = 'proto.message_pb2'
  # @@protoc_insertion_point(class_scope:tfedlrn.ValidationAck)
  ))
_sym_db.RegisterMessage(ValidationAck)


# @@protoc_insertion_point(module_scope)
