# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tfedlrn.proto.message_pb2 as message__pb2


class AggregatorStub(object):
  """we start with everything as "required" while developing / debugging. This forces correctness better.
  FIXME: move to "optional" once development is complete

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Query = channel.unary_unary(
        '/tfedlrn_proto.Aggregator/Query',
        request_serializer=message__pb2.FLMessage.SerializeToString,
        response_deserializer=message__pb2.FLMessage.FromString,
        )


class AggregatorServicer(object):
  """we start with everything as "required" while developing / debugging. This forces correctness better.
  FIXME: move to "optional" once development is complete

  """

  def Query(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AggregatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=message__pb2.FLMessage.FromString,
          response_serializer=message__pb2.FLMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tfedlrn_proto.Aggregator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
