name: Build and Push Openfl Docker Image

on:
  push:
    branches: 
      - develop
      - v1.7.x
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        default: 'latest'

env:
  VERSION: ${{ github.ref == 'refs/heads/develop' && 'latest' || '1.7' }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push OpenFL Base Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: openfl-docker/Dockerfile.base
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/openfl:${{ github.event.inputs.version || 'latest' }}
