name: Build and Push Openfl Docker Image

on:
  push:
    branches: 
      - develop
      - v1.7.x
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the Docker image with'
        required: false
        default: 'latest'

env:
  DEFAULT_VERSION: ${{ 
    github.ref == 'refs/heads/develop' && 'latest' || 
    github.ref == 'refs/heads/v1.7.x' && '1.7' || 
    'fail' }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:      
    - name: Fail if invalid branch
      if: env.DEFAULT_VERSION == 'fail'
      run: |
        echo "Invalid branch. The workflow only supports 'develop' or 'v1.7.x'."
        exit 1

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Determine Image Tag
      run: echo "IMAGE_TAG=${{ github.event.inputs.version || env.DEFAULT_VERSION }}" >> $GITHUB_ENV

    - name: Build and Push OpenFL Base Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: openfl-docker/Dockerfile.base
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/openfl:${{ env.IMAGE_TAG }}
